apiVersion: v1
kind: PersistentVolume
metadata: 
  name: odoo-web-addons-vol
spec: 
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/volume/odoo-web-addons"