apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres-svc
  namespace: odoo
  labels: 
    app: odoo-postgres-service
spec: 
  type: NodePort
  ports:
    - port: 5432
      nodePort: 31456
  selector:
    app: odoo-postgres
