apiVersion: v1
kind: Service
metadata:
  name: odoo-web-svc
  namespace: odoo
  labels: 
    app: odoo-web-service
spec: 
  type: NodePort
  ports:
    - port: 8069
      nodePort: 31457
  selector:
    app: odoo-web
